project:
  type: website
  output-dir: docs

website:
  title: "Rebecca Larsen"
  navbar: 
    right: 
    - href: index.qmd
      text: Home 
    - href: about.qmd
      text: About 
    - href: CV.pdf
      text: CV 
    - href: assignments.qmd
      text: Assignments 


format:
  html:
    theme: minty
    css: styles.css
    toc: true
    

quarto publish


