---
title: "Research and Creative Contributions"
editor: visual
---

### Conference Presentations

Southern Political Science Association 2024

-   Larsen, R. (2024). "Natural Cause Deaths: A Survey of Public Perceptions."\
    [Link to Presentation](https://rebeccalarsen.github.io/SPSA.pdf).

-   Larsen, R. (2024). "Impacts of State-Level Bail Reform."\
    [Link to Presentation](https://rebeccalarsen.github.io/SPSA2.pdf).

American Political Science Association 2023

-   Larsen, R. (2023). "Cash Bail Reform: Testing Competing Political Expectations."\
    [Link to Presentation](https://rebeccalarsen.github.io/APSA.pdf).

Midwest Political Science Association 2022 - Pedagogical Contributions

-   Larsen, R. (2022). *Online Courses and Student Engagement*. Chair of Panel. Midwest Political Science Association.

-   Larsen, R. (2022). *Being Faculty at a Regional University*. Panel Discussant. Midwest Political Science Association.

-   Larsen, R**.** (2022).*Experiential Learning in the Classroom*. Panel Discussant. Midwest Political Science Association. 

Southern States Communication Association 2021

-   Lastrape, A. & Larsen, R. (2021). "'I Call it Matilda's Law': Governor's Presidential Rhetoric."

### Broadcast Contributions

Larsen, R. & Lastrape, A. (April 2020 - Spring 2022). [This is for the CV](https://podcasters.spotify.com/pod/show/thisisforthecv). Podcast. Editor, Co-host, Co-creator. A podcast about politics and education by educators from different disciplines, backgrounds, and world views.

### Sample of Community/Nonprofit Contributions

-   [The Impact of Bail on McLennan County](https://rebeccalarsen.github.io/wacobail.pdf). Example from Stage 3 of project update to stakeholders.

-   Claitor, D., Young, A.L., Ling, E., Larsen, R. (2016). [Jailhouse Stories: Voices of Pretrial Detention in Texas](https://www.jailhousestories.org/). *Texas Jail Project*.

-   Dunklee, C. & Larsen, R. (2015). [Examining the praised Texas prison reform model: How Texas is maintaining racial disparity and mass incarceration](https://www.prisonlegalnews.org/media/publications/Examining%20the%20TX%20Prison%20Reform%20Model,%20Institute%20for%20Urban%20Policy%20Research%20%26%20Analysis,%202015.pdf). *The Institute of Urban Policy Research and Analysis*, The University of Texas at Austin.

### Manuscripts in Progress

-   Larsen, R. (2024). "Natural Cause Jail Deaths: A Survey of Public Perceptions."\
    [Paper Draft](https://rebeccalarsen.github.io/JailDeaths.pdf)

-   Larsen, R. (2023). "Cash Bail Reform: Testing Competing Political Expectations."\
    [Paper Draft](https://rebeccalarsen.github.io/BailReform.pdf)

-   Larsen, R. (2023). "Rights Violations in Texas Jails: A Text Analysis of Noncompliant Jails."\
    [Paper Draft](https://rebeccalarsen.github.io/TextAnalysis.pdf)

-   Larsen, R. (2023). "Cash Bail's Impact on Crime: A Meta-Analysis Proposal."\
    [Paper Draft](https://rebeccalarsen.github.io/Meta2.pdf)\
    [Presentation](https://rebeccalarsen.github.io/MetaAnalysis.pdf)

-   Khan, H., Larsen, R., & Stewart, S. (2023). Exploring the Sentiment of Qatar World Cup Tweets.\
    [Paper Draft](https://rebeccalarsen.github.io/finalproject.pdf)

-   Larsen, R. (2022). "The Political Legacy of Slavery: Replicating and Testing the Path Dependence Theory on a Criminal Justice Outcome."\
    [Paper Draft](https://rebeccalarsen.github.io/Path.pdf)
